#!/bin/bash
#
# Used by Travis to submit named assets to the correct environments.

set -euo pipefail

if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  case ${TRAVIS_BRANCH} in
    master)
      echo "Submitting to production."
      export CONTENT_STORE_URL=https://developer.rackspace.com:9000/
      export CONTENT_STORE_APIKEY=${PROD1}${PROD2}${PROD3}
      ;;
    redesign)
      echo "Submitting to staging."
      export CONTENT_STORE_URL=http://staging.developer.rackspace.com:8000/
      export CONTENT_STORE_APIKEY=${STAGE1}${STAGE2}${STAGE3}
      ;;
    *)
      echo "Not submitting ${TRAVIS_BRANCH} anywhere."
      ;;
  esac
else
  echo "Not submitting pull request build anywhere."
fi

deconst-preparer-jekyll

# Show all the categories to help authors know which categories are available
jekyll-audit categories list --posts-dir ${TRAVIS_BUILD_DIR}/_posts

# Will fail if any underused categories have been created
jekyll-audit categories list-underused --posts-dir ${TRAVIS_BUILD_DIR}/_posts
